### ISSUE TITLE
Allow closing of tile programmatically

### ISSUE THREAD

**Issue by davidpanic** [Skylled/expansion_tile_card#15] opened 2020-10-07 10:50 UTC
I just want to be able to close the expansion tile by calling some function.
That would enable the implementation of only allowing one expansion tile to be open at a time.

**Comment by Skylled** [comment] 2020-10-07 15:13
Duplicate of #10.

Feel free to re-open with an explanation if the `currentState.collapse()` solution doesn't cover your use case.

**Comment by Skylled** [comment] 2020-10-07 15:14
I'll make a note to include an example in the Readme and the demo app showing how to do this.

**Closed as completed by Skylled** 2020-10-07 15:13 UTC
